################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../KCG/AutoBrake.c \
../KCG/AutoBrake_EnabletoDisArm.c \
../KCG/AutobrakeArmedtoDisarmed.c \
../KCG/Autobrake_ARM_Application.c \
../KCG/Autobrake_ARMtoEnable.c \
../KCG/Autobrake_Application_Disarmed.c \
../KCG/Autobrake_EnaletoApplication.c \
../KCG/BTI.c \
../KCG/BoolVect2Int16_digital_3.c \
../KCG/Brake.c \
../KCG/BrakeInhibit.c \
../KCG/BrakePress.c \
../KCG/BrakeSelect.c \
../KCG/Brake_Skid.c \
../KCG/Counter.c \
../KCG/LimiterF32.c \
../KCG/Lockwheel.c \
../KCG/OFFtoAutobrakeArmed.c \
../KCG/OFFtoRTOArmed.c \
../KCG/PI_Control.c \
../KCG/PedalF.c \
../KCG/RTOApplicationDisarmed_.c \
../KCG/RTOArmedtoDisarmed_.c \
../KCG/RTOArmedtoEnabled.c \
../KCG/RTOEnabledtoApplication.c \
../KCG/RTOEnabledtoDisarmed_.c \
../KCG/SC_Function.c \
../KCG/SC_LowSpeedMonitor.c \
../KCG/SC_SlipControl.c \
../KCG/SC_Wheel.c \
../KCG/Spindown.c \
../KCG/TDP.c \
../KCG/WOW_Processing.c \
../KCG/equ_2.c \
../KCG/equ_3.c \
../KCG/equ_4.c \
../KCG/equ_5.c \
../KCG/equ_6.c \
../KCG/kcg_consts.c \
../KCG/kcg_types.c \
../KCG/sigle.c \
../KCG/stm.c 

C_DEPS += \
./KCG/AutoBrake.d \
./KCG/AutoBrake_EnabletoDisArm.d \
./KCG/AutobrakeArmedtoDisarmed.d \
./KCG/Autobrake_ARM_Application.d \
./KCG/Autobrake_ARMtoEnable.d \
./KCG/Autobrake_Application_Disarmed.d \
./KCG/Autobrake_EnaletoApplication.d \
./KCG/BTI.d \
./KCG/BoolVect2Int16_digital_3.d \
./KCG/Brake.d \
./KCG/BrakeInhibit.d \
./KCG/BrakePress.d \
./KCG/BrakeSelect.d \
./KCG/Brake_Skid.d \
./KCG/Counter.d \
./KCG/LimiterF32.d \
./KCG/Lockwheel.d \
./KCG/OFFtoAutobrakeArmed.d \
./KCG/OFFtoRTOArmed.d \
./KCG/PI_Control.d \
./KCG/PedalF.d \
./KCG/RTOApplicationDisarmed_.d \
./KCG/RTOArmedtoDisarmed_.d \
./KCG/RTOArmedtoEnabled.d \
./KCG/RTOEnabledtoApplication.d \
./KCG/RTOEnabledtoDisarmed_.d \
./KCG/SC_Function.d \
./KCG/SC_LowSpeedMonitor.d \
./KCG/SC_SlipControl.d \
./KCG/SC_Wheel.d \
./KCG/Spindown.d \
./KCG/TDP.d \
./KCG/WOW_Processing.d \
./KCG/equ_2.d \
./KCG/equ_3.d \
./KCG/equ_4.d \
./KCG/equ_5.d \
./KCG/equ_6.d \
./KCG/kcg_consts.d \
./KCG/kcg_types.d \
./KCG/sigle.d \
./KCG/stm.d 

OBJS += \
./KCG/AutoBrake.obj \
./KCG/AutoBrake_EnabletoDisArm.obj \
./KCG/AutobrakeArmedtoDisarmed.obj \
./KCG/Autobrake_ARM_Application.obj \
./KCG/Autobrake_ARMtoEnable.obj \
./KCG/Autobrake_Application_Disarmed.obj \
./KCG/Autobrake_EnaletoApplication.obj \
./KCG/BTI.obj \
./KCG/BoolVect2Int16_digital_3.obj \
./KCG/Brake.obj \
./KCG/BrakeInhibit.obj \
./KCG/BrakePress.obj \
./KCG/BrakeSelect.obj \
./KCG/Brake_Skid.obj \
./KCG/Counter.obj \
./KCG/LimiterF32.obj \
./KCG/Lockwheel.obj \
./KCG/OFFtoAutobrakeArmed.obj \
./KCG/OFFtoRTOArmed.obj \
./KCG/PI_Control.obj \
./KCG/PedalF.obj \
./KCG/RTOApplicationDisarmed_.obj \
./KCG/RTOArmedtoDisarmed_.obj \
./KCG/RTOArmedtoEnabled.obj \
./KCG/RTOEnabledtoApplication.obj \
./KCG/RTOEnabledtoDisarmed_.obj \
./KCG/SC_Function.obj \
./KCG/SC_LowSpeedMonitor.obj \
./KCG/SC_SlipControl.obj \
./KCG/SC_Wheel.obj \
./KCG/Spindown.obj \
./KCG/TDP.obj \
./KCG/WOW_Processing.obj \
./KCG/equ_2.obj \
./KCG/equ_3.obj \
./KCG/equ_4.obj \
./KCG/equ_5.obj \
./KCG/equ_6.obj \
./KCG/kcg_consts.obj \
./KCG/kcg_types.obj \
./KCG/sigle.obj \
./KCG/stm.obj 

OBJS__QUOTED += \
"KCG\AutoBrake.obj" \
"KCG\AutoBrake_EnabletoDisArm.obj" \
"KCG\AutobrakeArmedtoDisarmed.obj" \
"KCG\Autobrake_ARM_Application.obj" \
"KCG\Autobrake_ARMtoEnable.obj" \
"KCG\Autobrake_Application_Disarmed.obj" \
"KCG\Autobrake_EnaletoApplication.obj" \
"KCG\BTI.obj" \
"KCG\BoolVect2Int16_digital_3.obj" \
"KCG\Brake.obj" \
"KCG\BrakeInhibit.obj" \
"KCG\BrakePress.obj" \
"KCG\BrakeSelect.obj" \
"KCG\Brake_Skid.obj" \
"KCG\Counter.obj" \
"KCG\LimiterF32.obj" \
"KCG\Lockwheel.obj" \
"KCG\OFFtoAutobrakeArmed.obj" \
"KCG\OFFtoRTOArmed.obj" \
"KCG\PI_Control.obj" \
"KCG\PedalF.obj" \
"KCG\RTOApplicationDisarmed_.obj" \
"KCG\RTOArmedtoDisarmed_.obj" \
"KCG\RTOArmedtoEnabled.obj" \
"KCG\RTOEnabledtoApplication.obj" \
"KCG\RTOEnabledtoDisarmed_.obj" \
"KCG\SC_Function.obj" \
"KCG\SC_LowSpeedMonitor.obj" \
"KCG\SC_SlipControl.obj" \
"KCG\SC_Wheel.obj" \
"KCG\Spindown.obj" \
"KCG\TDP.obj" \
"KCG\WOW_Processing.obj" \
"KCG\equ_2.obj" \
"KCG\equ_3.obj" \
"KCG\equ_4.obj" \
"KCG\equ_5.obj" \
"KCG\equ_6.obj" \
"KCG\kcg_consts.obj" \
"KCG\kcg_types.obj" \
"KCG\sigle.obj" \
"KCG\stm.obj" 

C_DEPS__QUOTED += \
"KCG\AutoBrake.d" \
"KCG\AutoBrake_EnabletoDisArm.d" \
"KCG\AutobrakeArmedtoDisarmed.d" \
"KCG\Autobrake_ARM_Application.d" \
"KCG\Autobrake_ARMtoEnable.d" \
"KCG\Autobrake_Application_Disarmed.d" \
"KCG\Autobrake_EnaletoApplication.d" \
"KCG\BTI.d" \
"KCG\BoolVect2Int16_digital_3.d" \
"KCG\Brake.d" \
"KCG\BrakeInhibit.d" \
"KCG\BrakePress.d" \
"KCG\BrakeSelect.d" \
"KCG\Brake_Skid.d" \
"KCG\Counter.d" \
"KCG\LimiterF32.d" \
"KCG\Lockwheel.d" \
"KCG\OFFtoAutobrakeArmed.d" \
"KCG\OFFtoRTOArmed.d" \
"KCG\PI_Control.d" \
"KCG\PedalF.d" \
"KCG\RTOApplicationDisarmed_.d" \
"KCG\RTOArmedtoDisarmed_.d" \
"KCG\RTOArmedtoEnabled.d" \
"KCG\RTOEnabledtoApplication.d" \
"KCG\RTOEnabledtoDisarmed_.d" \
"KCG\SC_Function.d" \
"KCG\SC_LowSpeedMonitor.d" \
"KCG\SC_SlipControl.d" \
"KCG\SC_Wheel.d" \
"KCG\Spindown.d" \
"KCG\TDP.d" \
"KCG\WOW_Processing.d" \
"KCG\equ_2.d" \
"KCG\equ_3.d" \
"KCG\equ_4.d" \
"KCG\equ_5.d" \
"KCG\equ_6.d" \
"KCG\kcg_consts.d" \
"KCG\kcg_types.d" \
"KCG\sigle.d" \
"KCG\stm.d" 

C_SRCS__QUOTED += \
"../KCG/AutoBrake.c" \
"../KCG/AutoBrake_EnabletoDisArm.c" \
"../KCG/AutobrakeArmedtoDisarmed.c" \
"../KCG/Autobrake_ARM_Application.c" \
"../KCG/Autobrake_ARMtoEnable.c" \
"../KCG/Autobrake_Application_Disarmed.c" \
"../KCG/Autobrake_EnaletoApplication.c" \
"../KCG/BTI.c" \
"../KCG/BoolVect2Int16_digital_3.c" \
"../KCG/Brake.c" \
"../KCG/BrakeInhibit.c" \
"../KCG/BrakePress.c" \
"../KCG/BrakeSelect.c" \
"../KCG/Brake_Skid.c" \
"../KCG/Counter.c" \
"../KCG/LimiterF32.c" \
"../KCG/Lockwheel.c" \
"../KCG/OFFtoAutobrakeArmed.c" \
"../KCG/OFFtoRTOArmed.c" \
"../KCG/PI_Control.c" \
"../KCG/PedalF.c" \
"../KCG/RTOApplicationDisarmed_.c" \
"../KCG/RTOArmedtoDisarmed_.c" \
"../KCG/RTOArmedtoEnabled.c" \
"../KCG/RTOEnabledtoApplication.c" \
"../KCG/RTOEnabledtoDisarmed_.c" \
"../KCG/SC_Function.c" \
"../KCG/SC_LowSpeedMonitor.c" \
"../KCG/SC_SlipControl.c" \
"../KCG/SC_Wheel.c" \
"../KCG/Spindown.c" \
"../KCG/TDP.c" \
"../KCG/WOW_Processing.c" \
"../KCG/equ_2.c" \
"../KCG/equ_3.c" \
"../KCG/equ_4.c" \
"../KCG/equ_5.c" \
"../KCG/equ_6.c" \
"../KCG/kcg_consts.c" \
"../KCG/kcg_types.c" \
"../KCG/sigle.c" \
"../KCG/stm.c" 


