#ifndef USER_MACROS_H
#define USER_MACROS_H
/*generated by SCADE Code Generator*/
/*#include "libraries/SC65/libmathext/macro_libmathext64.h"*/
/*#include "libraries/SC65/libmathext/macro_libmathext32.h"*/
#endif /*USER_MACROS_H*/
